platform :ios, '8.0'

target "myOCProject" do

pod 'ReactiveCocoa', '~> 2.5'
pod 'SDWebImage', '~> 3.7.5'
pod 'JSONModel', '~> 1.0.1'
pod 'FMDB/SQLCipher', '~>2.5'
pod 'XAspect'
pod 'IQKeyboardManager'
pod 'LBXScan','~> 1.1.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'MWPhotoBrowser'
pod 'LBXScan','~> 1.1.1'
pod 'M13ProgressSuite', '~> 1.2.7'
pod 'pop'
pod 'YYText'
pod 'AMapLocation'
pod 'LCActionSheet'
pod 'CocoaAsyncSocket'
pod 'SAMKeychain'
pod 'AFNetworking'
pod 'CocoaLumberjack'
end
